1 - Создайте NumPy array с элементами от числа N до 0.
N не входит в массив. Для N = 10 результат будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

Важно: не удаляйте код ниже, а дополните его. Функция необходима для проверки вашего решения. Функция принимает целое число и возвращает np.array.

In [2]:
import numpy as np

In [3]:
def my_array(int):
    a = np.arange(int-1, -1,-1)
    return a
 
print(my_array(10))
print(my_array(15))
print(my_array(20))

[9 8 7 6 5 4 3 2 1 0]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


2 - Создайте диагональную матрицу с элементами от N до 0 (N входит в массив).
Посчитайте сумму её значений на диагонали.

Важно: не удаляйте код ниже, а дополните его. Функция необходима для проверки вашего решения. Функция принимает целое число и возвращает целое число.

In [8]:
def sum_matrix(int) :
    my_matrix = np.sum(np.diag(np.arange(1, int+1)))
    return my_matrix
 
print(sum_matrix(5))
print(sum_matrix(10))
print(sum_matrix(15))

15
55
120


Условие задачи
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем

Матрица в виде numpy array

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
На сайт заходит очередной посетитель, о покупках которого известно следующее:

1
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
Найдите индекс самого похожего пользователя max_index, т.е. посчитайте косинусное сходство между этим пользователем и каждым из пользователей из массива user_stats.
Нумерацию индексов следует начинать с 0.
Впишите свое решение вместо " …"

Важно: не удаляйте код ниже, а дополните его. Функция необходима для проверки вашего решения. Функция принимает матрицу и массив и возвращает целое число – ИНДЕКС самого похожего пользователя

In [9]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine(matrix, user):
    max_index = 0
    user_index = 0
    for i, a in enumerate(matrix):
        userr = np.array(user)
        cc = np.dot(userr, a) / ((np.linalg.norm(userr)) * (np.linalg.norm(a)))
        if cc > max_index:
            user_index = i
    
    
    return user_index

print(cosine(users_stats, next_user_stats))

7
