In [1]:
import numpy as np

In [18]:
x = np.array([4,3])
y = np.array([2,1])

In [3]:
type(x)

numpy.ndarray

In [4]:
x.shape


(3,)

In [11]:
np.diag(np.arange(2,50,15), k=-2)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 2,  0,  0,  0,  0,  0],
       [ 0, 17,  0,  0,  0,  0],
       [ 0,  0, 32,  0,  0,  0],
       [ 0,  0,  0, 47,  0,  0]])

In [22]:
a = np.dot(x,y)
c = np.linalg.norm(x)
b = 

In [29]:
aa = ((a)/((np.linalg.norm(x)) * (np.linalg.norm(y))))

In [30]:
np.arccos(aa)

np.float64(0.17985349979247847)

In [ ]:
Найдите индекс самого похожего пользователя max_index, т.е. посчитайте косинусное сходство между этим пользователем и каждым из пользователей из массива user_stats.
Нумерацию индексов следует начинать с 0.
Впишите свое решение вместо " …"

Важно: не удаляйте код ниже, а дополните его. Функция необходима для проверки вашего решения. Функция принимает матрицу и массив и возвращает целое число – ИНДЕКС самого похожего пользователя

In [93]:
import numpy as np
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine(matrix, user):
    max_index = 0
    user_index = 0
    for i, a in enumerate(matrix):
        userr = np.array(user)
        cc = np.dot(userr, a) / ((np.linalg.norm(userr)) * (np.linalg.norm(a)))
        if cc > max_index:
            user_index = i
    
    
    return user_index

print(cosine(users_stats, next_user_stats))
    

7


In [89]:

Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

Важно: не удаляйте код ниже, а дополните его. Функция необходима для проверки вашего решения. Она должна вернуть массив чисел с плавающей точкой.
    



1
5
2
5
2
0
0
3
0
0


In [20]:
import numpy as np
from numpy import linalg 


a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
np.allclose( np.dot(a, linalg.solve(a, b)), b )
 

True

In [16]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [19]:
def sys_lin_eq() :
    a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
    b = np.array([4, 12, -3])
    return linalg.solve(a, b)

print(sys_lin_eq())

[ 0.46666667  3.84444444 -5.55555556]
